services:
  mysql:
    image: mysql:8.0
    container_name: mysql_starwars
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: starwarsBD
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - '3307:3306'
    volumes:
      - challenge-rimac_mysql_data:/var/lib/mysql
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql

  redis:
    image: redis:latest
    container_name: redis_starwars
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --appendonly yes
    volumes:
      - challenge-rimac_redis_data:/data

volumes:
  challenge-rimac_mysql_data:
  challenge-rimac_redis_data:
