export const SOURCE_COMPONENT_NAME = "fn-challenge-rimac";
export const ERROR_NO_CONEXION = "ECONNREFUSED";

export const planetCityMap = new Map<string, string>([
	["Tatooine", "Riyadh"],
	["Alderaan", "Zúrich"],
	["Yavin IV", "Manaos"],
	["Hoth", "Nuuk"],
	["Dagobah", "Pantanal"],
	["Bespin", "Denver"],
	["Endor", "Vancouver"],
	["Naboo", "Florencia"],
	["Coruscant", "Nueva York"],
	["Kamino", "Malé"],
	["Geonosis", "Las Vegas"],
	["Utapau", "Amán"],
	["Mustafar", "Hilo"],
	["Kashyyyk", "Belém"],
	["Polis Massa", "Atacama"],
	["Mygeeto", "Barrow"],
	["Felucia", "Kuala Lumpur"],
	["Cato Neimoidia", "Auckland"],
	["Saleucami", "Phoenix"],
	["Stewjon", "Buenos Aires"],
	["Eriadu", "Beijing"],
	["Corellia", "Londres"],
	["Rodia", "Bangkok"],
	["Nal Hutta", "Lagos"],
	["Dantooine", "Nairobi"],
	["Bestine IV", "Sídney"],
	["Ord Mantell", "Buenos Aires"],
	["Trandosha", "Cusco"],
	["Socorro", "Dubái"],
	["Mon Cala", "Honolulu"],
	["Chandrila", "Berlín"],
	["Sullust", "Reikiavik"],
	["Toydaria", "Nueva Orleans"],
	["Malastare", "Ciudad de México"],
	["Dathomir", "Johannesburgo"],
	["Ryloth", "Marrakech"],
	["Aleen Minor", "Antártida"],
	["Vulpter", "Nueva Delhi"],
	["Troiken", "El Cairo"],
	["Tund", "Atacama"],
	["Haruun Kal", "Nápoles"],
	["Cerea", "Medellín"],
	["Glee Anselm", "Jakarta"],
	["Iridonia", "Cusco"],
	["Tholoth", "Antártida"],
	["Iktotch", "La Paz"],
	["Quermia", "Antártida"],
	["Dorin", "San Francisco"],
	["Champala", "Cartagena"],
	["Mirial", "El Cairo"],
	["Serenno", "Manaos"],
	["Concord Dawn", "Kuala Lumpur"],
	["Zolan", "Antártida"],
	["Ojom", "Reikiavik"],
	["Skako", "Singapur"],
	["Muunilinst", "Praga"],
	["Shili", "Dakar"],
	["Kalee", "Manaos"],
	["Umbara", "Antártida"]
]);

export const API_SWAPI_URL = "https://swapi.dev/api/";
export const WEATHER_API_URL = "https://api.weatherapi.com/v1/";

